# Variables
@baseUrl = http://localhost:3333

# health check
GET {{baseUrl}}/health

###

# Get rooms
GET {{baseUrl}}/rooms

###

# Create room
POST {{baseUrl}}/rooms
Accept: application/json
Content-Type: application/json

{
  "name": "Sala de teste",
  "description": "Esta é uma sala de teste criada via API"
}
